export const questions = [
    {
      id: 1,
      question: "which of the following methods cannot prevent object modification",
      answer_a: "Object.seal()",
      answer_b: "Object.lock()",
      answer_c: "Object.preventExtension()",
      answer_d: "Object.freeze()",
      correct_answer: "b",
    },
    {
      id: 2,
      question: "which of the following is the correct way to store data in an object",
      answer_a: "obj['class'] = 12",
      answer_b: "obj.class = 12",
      answer_c: "a & b",
      answer_d: "None of above",
      correct_answer: "c",
    },
    {
      id: 3,
      question: "If you have a function f and an object o, you can define a method named m of o with",
      answer_a: "o.m=m.f;",
      answer_b: "o.m=f;",
      answer_c: "o=f.m;",
      answer_d: "o=f;",
      correct_answer: "a",
    },
    {
    id: 4,
    question: "How much is 2+4*5+1 = ? ",
    answer_a: "23",
    answer_b: "36",
    answer_c: "31",
    answer_d: "26",
    correct_answer: "a",
      },
  ];